### PR TITLE
Fix for pending takes not cleaned up when they timeout

### LINKED ISSUE #194: try-take! fills :pending-takes even after timeout
When attempting to fetch from a stream, and expecting it to fail with a timeout with try-take!, :pending-takes is still incremented and results in an exception with excessive pending takes. Maybe I am using it incorrectly, but I would expect that timed-out takes would result in no mutated state of the stream since they would no longer be relevant.

```
enki.buffers> (def y (stream/stream))
#'enki.buffers/y
enki.buffers> (dotimes [n 16384] (stream/try-take! y 1))
nil
enki.buffers> y
<< stream: {:pending-puts 0, :drained? false, :buffer-size 0, :permanent? false, :type "manifold", :sink? true, :closed? false, :pending-takes 16384, :buffer-capacity 0, :source? true} >>
enki.buffers> (stream/try-take! y 1)
Jan 27, 2021 11:29:29 PM clojure.tools.logging$eval451$fn__455 invoke
WARNING: excessive pending takes (> 16384), closing stream
java.lang.IllegalStateException
	at manifold.stream.default.Stream.take(default.clj:234)
	at enki.buffers$eval38629.invokeStatic(form-init9188607286898067210.clj:17367)
	at enki.buffers$eval38629.invoke(form-init9188607286898067210.clj:17367)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7132)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at nrepl.middleware.interruptible_eval$evaluate$fn__29511$fn__29512.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate$fn__29511.invoke(interruptible_eval.clj:87)
	at clojure.main$repl$read_eval_print__9086$fn__9089.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9086.invoke(main.clj:437)
	at clojure.main$repl$fn__9095.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__29542$fn__29546.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__29609$fn__29613.invoke(session.clj:202)
	at nrepl.middleware.session$session_exec$main_loop__29609.invoke(session.clj:201)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:832)#<SuccessDeferred@11f12ad4: false>
enki.buffers> (def y (stream/stream))
#'enki.buffers/y
enki.buffers> (dotimes [n 16384] (stream/try-take! y 1))
nil
enki.buffers> (stream/put! y 1)
#<Deferred@50a88030: :not-delivered>
enki.buffers> (stream/try-take! y 1)
#<SuccessDeferred@6429f73e: 1>
enki.buffers> y
<< stream: {:pending-puts 0, :drained? false, :buffer-size 0, :permanent? false, :type "manifold", :sink? true, :closed? false, :pending-takes 0, :buffer-capacity 0, :source? true} >>```

My use case is fetching from the stream, and if I encounter a timeout, I pass the data I collected up until that point to a function and then loop (not blocking on fetches, but flushing what I have and then waiting for more.) Currently this behaviour would result in the stream getting closed.

Apologies if this is incorrect usage, but it seems like maybe a bug?

### PR DESCRIPTION
**Pull request by KingMob**
## About
Fixes #194 by cleaning the pending put/take lists every X calls

## Changes

- Periodically cleans up pending takes/puts, and removes any that have been realized (presumably due to timeout)
- Fixes value returned when the number of takes exceeds the limit, to match the documentation
- Adds tests
- Defines vars for the put/take limits and how often to check, in case anybody wants to tune those

#### Internal details
Producer and Consumer were changed from types to records. We need to access the `deferred` field in both, but that incurs a reflection penalty in the cleanup fn. The choice was between making a duplicate cleanup fn, adding a protocol to access `.-deferred` and hinting with that, or switching to records and using keyword access.

I'd rather not make a duplicate fn that's 99% the same, and a macro feels like a bit much just for this. I checked with Criterium, and keyword access is only 25% slower (ditto for a new protocol) but still just a few nanoseconds, so this seems acceptable.

### CODE REVIEW

**Comment by KingMob** [comment]
For some reason, I can't choose @kachayev as a reviewer. @slipset do you know what that's about?

Also Erik, you added CircleCI support, so I'm going to remove the Travis support unless I hear someone say otherwise; it seems to be failing. I'll add support for more JDKs later.

**Comment by slipset** [comment]
Should be fine to remove travis. I've also invited @kachayev as a maintainer of manifold

**Comment by wdullaer** [comment]
Would it be possible to make the `max-dirty-takes`/`max-dirty-puts` configurable?
I have a usecase where I have very little puts and takes, but it is important that there are no timed out takes at all still in the queue. Right now I need to send dummy messages on the stream to ensure the dirty takes are cleaned out.

**Comment by KingMob** [comment]
@wdullaer I'm a bit unclear as to what you're asking here.

For starters, `max-dirty-takes/max-dirty-puts` can already be reconfigured with `alter-var-root` and `constantly` to a different value. 

Backing up a bit, what problem are you running into that you're trying to prevent timed-out takes? Couldn't you use `take!` over `try-take!` for that?

**Comment by wdullaer** [comment]
I forgot about `alter-var-root`, that would indeed work.

My issue is a bit involved: I have some code that polls a web endpoint, and returns a function to cancel this polling to the caller.
In my initial implementation, I had the cancel function set a deferred to success and used d/alt in my loop.
Unfortunately this ties the lifetime of all the http deferreds with the cancel deferred together. Because the cancel deferred typically lives for the entire program, it causes a big memory leak.

My solution is to have the cancel function pop a message on a stream, and do a take! in each loop. The deferred from the take! can then be put in the alt. At the end of the loop, I can set this take! deferred to success and have it pruned from the pending consumers on the stream.
It's important those completed deferreds are pruned right away, because the polling can take some time to reach 64 iterations (it's an event loop, sometimes there's a lot, sometimes there's none).

Right now, I hack around this by putting dummy messages on the stream to realize the take! deferred, but it's a bit ugly.

**Comment by KingMob** [comment]
@wdullaer Hmm. I'm guessing your original solution used alt in a loop to choose between the next http polling stream value and the cancellation deferred? Yeah, that would tie the alt deferreds to the cancellation deferred through the on-realized callbacks. I would have thought the http deferreds would clean up once they resolve, though. Of course, the alt deferreds would usually hold the http deferreds value, so that's still a big leak if they don't get cleaned up.

The best solution would be to cancel the callbacks on the unresolved deferreds, which should be a matter of switching from `on-realized` to using `add-listener/cancel-listener`. However, not all of them are currently cancellable. If it's a Future or an IPending, the "callbacks" are actually tasks submitted to an Executor that block on the realized value of the Future. Maybe that's not a problem, even if it's not a universal solution. Will have to think about this more. Would you be willing to write up an issue with some example code?

For your particular use case, instead of a stream that you continually take from and have to fill with dummy values, what about this? Use a single cancellation deferred and each loop, check to see if it's been realized. If realized, exit. If not realized, continue with the loop. To avoid blocking on the http deferreds if the loop's been canceled, use alt with a timeout on the http deferreds. This ensures it'll still check for cancellation, at the cost of a bit of CPU cycles.

**Comment by KingMob** [comment]
@ztellman @kachayev Do either of you want/have time to comment on this? If not, that's ok, I'll invite some of the other people who expressed interest in maintaining Manifold to take a look.

File: src/manifold/stream/default.clj [hunk 1]
```diff
@@ -38,6 +45,17 @@
     nil
     x))
 
+(defn- cleanup-expired-deferreds
+  "Removes all realized deferreds (presumably from timing out)."
+  [^LinkedList l]
+  (when-not (.isEmpty l)
```
Comment (ztellman) [inline src/manifold/stream/default.clj:51]: this should probably be synchronized on `l`, just to be safe

**Comment by ztellman** [comment]
Hi, sorry for not getting to this sooner.  This looks good, but it's at least theoretically possible for us to hit the `dirty-*` threshold concurrently on two separate threads, so it would be safest to put a `(locking l ...)` around `cleanup-expired-deferreds`.

File: src/manifold/stream/default.clj (hunk 1 above)
Comment (KingMob) [reply src/manifold/stream/default.clj:51]: Ahh, thanks for catching that, I'll update it.

**Review by ztellman — APPROVED** [review]
